import argparse


def get_train_args():
    parser = argparse.ArgumentParser()
    parser.add_argument("--decoder_size", type=str, default="1.5B",
                        choices=["0.5B", "1.5B", "3B", "7B"])
    parser.add_argument("--decoder_path", type=str, default=None)
    parser.add_argument("--vision_tower", type=str, default="dcformer",
                        choices=["dcformer", "dcformer_tiny", "vit3d"])
    parser.add_argument("--mm_projector_type", type=str, default="mixer",
                        choices=["mlp", "low_high_mlp", "mixer", "mhsa", "identity"])
    parser.add_argument("--mm_mlp_depth", type=int, default=2)
    parser.add_argument("--proj_out_num", type=int, default=256)
    parser.add_argument("--input_size", type=int, nargs=3, default=[256, 256, 128])
    parser.add_argument("--dim", type=int, default=768)
    parser.add_argument("--depth", type=int, default=12)
    parser.add_argument("--vision_select_layer", type=int, default=-2)
    parser.add_argument("--vision_select_feature", type=str, default="cls_patch")
    parser.add_argument("--use_ssa", action="store_true", default=True)
    parser.add_argument("--use_mssa", action="store_true", default=True)
    parser.add_argument("--ssa_layers", type=int, default=2)
    parser.add_argument("--mssa_layers", type=int, default=2)
    parser.add_argument("--mssa_heads", type=int, default=4)
    parser.add_argument("--max_slices", type=int, default=512)
    parser.add_argument("--dataset", type=str, default="radgenome",
                        choices=["radgenome", "pmcvqa", "m3d"])
    parser.add_argument("--data_root", type=str, default="./data")
    parser.add_argument("--radgenome_json", type=str,
                        default="./data/radgenome/radgenome_qa.json")
    parser.add_argument("--pmcvqa_json", type=str,
                        default="./data/pmcvqa/pmcvqa_ct.json")
    parser.add_argument("--cap_data_path", type=str,
                        default="./data/M3D_Cap_npy/M3D_Cap.json")
    parser.add_argument("--vqa_data_train_path", type=str,
                        default="./data/M3D-VQA/M3D_VQA_train.csv")
    parser.add_argument("--vqa_data_val_path", type=str,
                        default="./data/M3D-VQA/M3D_VQA_val.csv")
    parser.add_argument("--use_visual_prompt", action="store_true", default=False)
    parser.add_argument("--prompt_color", type=str, default="blue",
                        choices=["blue", "red", "green"])
    parser.add_argument("--prompt_thickness", type=int, default=3)
    parser.add_argument("--mask_dir", type=str, default="./data/masks")
    parser.add_argument("--lora_enable", action="store_true", default=True)
    parser.add_argument("--lora_r", type=int, default=16)
    parser.add_argument("--lora_alpha", type=int, default=32)
    parser.add_argument("--lora_dropout", type=float, default=0.05)
    parser.add_argument("--freeze_vision", action="store_true", default=True)
    parser.add_argument("--freeze_projector", action="store_true", default=True)
    parser.add_argument("--pretrain_vision_model", type=str, default=None)
    parser.add_argument("--pretrain_mm_adapter", type=str, default=None)
    parser.add_argument("--pretrain_mllm", type=str, default=None)
    parser.add_argument("--epochs", type=int, default=25)
    parser.add_argument("--batch_size", type=int, default=4)
    parser.add_argument("--grad_accum_steps", type=int, default=1)
    parser.add_argument("--lr", type=float, default=2e-5)
    parser.add_argument("--weight_decay", type=float, default=0.02)
    parser.add_argument("--warmup_steps", type=int, default=500)
    parser.add_argument("--lr_scheduler", type=str, default="cosine")
    parser.add_argument("--max_length", type=int, default=512)
    parser.add_argument("--focal_gamma", type=float, default=2.0)
    parser.add_argument("--lambda_cls", type=float, default=1.0)
    parser.add_argument("--lambda_gen", type=float, default=1.0)
    parser.add_argument("--lambda_reg", type=float, default=1e-4)
    parser.add_argument("--use_distill", action="store_true", default=False)
    parser.add_argument("--distill_epochs", type=int, default=1)
    parser.add_argument("--teacher_path", type=str, default=None)
    parser.add_argument("--bf16", action="store_true", default=True)
    parser.add_argument("--gradient_checkpointing", action="store_true", default=False)
    parser.add_argument("--output_dir", type=str, default="./output/med3dvlm")
    parser.add_argument("--log_dir", type=str, default="./logs")
    parser.add_argument("--log_steps", type=int, default=10)
    parser.add_argument("--eval_steps", type=int, default=500)
    parser.add_argument("--save_steps", type=int, default=2000)
    parser.add_argument("--save_total_limit", type=int, default=2)
    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument("--num_workers", type=int, default=4)
    parser.add_argument("--local_rank", type=int, default=-1)
    parser.add_argument("--resume_from", type=str, default=None)
    return parser.parse_args()


def get_eval_args():
    parser = argparse.ArgumentParser()
    parser.add_argument("--decoder_size", type=str, default="1.5B")
    parser.add_argument("--decoder_path", type=str, default=None)
    parser.add_argument("--vision_tower", type=str, default="dcformer")
    parser.add_argument("--mm_projector_type", type=str, default="mixer")
    parser.add_argument("--mm_mlp_depth", type=int, default=2)
    parser.add_argument("--proj_out_num", type=int, default=256)
    parser.add_argument("--input_size", type=int, nargs=3, default=[256, 256, 128])
    parser.add_argument("--dim", type=int, default=768)
    parser.add_argument("--depth", type=int, default=12)
    parser.add_argument("--vision_select_layer", type=int, default=-2)
    parser.add_argument("--vision_select_feature", type=str, default="cls_patch")
    parser.add_argument("--use_ssa", action="store_true", default=True)
    parser.add_argument("--use_mssa", action="store_true", default=True)
    parser.add_argument("--ssa_layers", type=int, default=2)
    parser.add_argument("--mssa_layers", type=int, default=2)
    parser.add_argument("--mssa_heads", type=int, default=4)
    parser.add_argument("--max_slices", type=int, default=512)
    parser.add_argument("--dataset", type=str, default="radgenome")
    parser.add_argument("--data_root", type=str, default="./data")
    parser.add_argument("--radgenome_json", type=str,
                        default="./data/radgenome/radgenome_qa.json")
    parser.add_argument("--pmcvqa_json", type=str,
                        default="./data/pmcvqa/pmcvqa_ct.json")
    parser.add_argument("--use_visual_prompt", action="store_true", default=False)
    parser.add_argument("--prompt_color", type=str, default="blue")
    parser.add_argument("--prompt_thickness", type=int, default=3)
    parser.add_argument("--mask_dir", type=str, default="./data/masks")
    parser.add_argument("--checkpoint_path", type=str, required=True)
    parser.add_argument("--batch_size", type=int, default=1)
    parser.add_argument("--max_length", type=int, default=512)
    parser.add_argument("--max_new_tokens", type=int, default=256)
    parser.add_argument("--bf16", action="store_true", default=True)
    parser.add_argument("--output_dir", type=str, default="./eval_output")
    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument("--num_workers", type=int, default=4)
    return parser.parse_args()
